wandb:
  team_account_name: next-level-potato # 팀 계정
  project_repo: RE  # 프로젝트 레포 이름
  name: kbh # 실험자 명
  info: baseline_bert-base # 실험명

path:
  train_path: ./data/raw_data/train.csv  # ./data/preprocessed_data/train.preprocessed.csv
  dev_path: ./data/raw_data/train.csv    # ./data/preprocessed_data/valid.preprocessed.csv 
  test_path: ./data/raw_data/test_data.csv

data:
  shuffle: True

model:
  name: klue/bert-base
  best_model_path: ./best_model

train:
  seed: 42
  checkpoints_dir : "./checkpoints"
  save_total_limits : 3
  save_steps : 500
  num_train_epochs : 10
  early_stopping_patience : 4  # early stopping

  learning_rate : 1e-5

  train_batch_size : 16
  eval_batch_size : 16

  warmup_steps : 500
  weight_decay: 0.01

  logging_dir : "./logs"
  logging_steps : 100

  evaluation_strategy : "steps"
  eval_steps : 500

  load_best_model_at_end : True